## Using Table Expressions

***

### Import Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import random

import pyodbc

%matplotlib inline

pd.set_option('display.max_columns',None)
#pd.set_option('display.max_rows',None)
pd.set_option('display.width', 1000)
pd.option_context('float_format','{:.2f}'.format)

random.seed(0)
np.random.seed(0)
np.set_printoptions(suppress=True)

## Load Data from SQL database

### MSSQL

In [2]:
conn = pyodbc.connect('Driver={SQL Server};'
                      'Server=DESKTOP-ARQLULI\SQLEXPRESS2019;'
                      'Database=AdventureWorksLT2012;'
                      'Trusted_Connection=yes;')

In [3]:
#cursor = conn.cursor()

In [4]:
#cursor

In [5]:
#cursor.execute('SELECT * FROM SALESLT.Address')

## Challenge 1: Retrieve Product Information

In [6]:
pd.read_sql_query("SELECT P.ProductID, P.Name AS ProductName, PM.Name AS ProductModel, PM.Summary \
                   FROM SalesLT.Product AS P\
                   JOIN SalesLT.vProductModelCatalogDescription AS PM \
                   ON P.ProductModelID = PM.ProductModelID \
                   ORDER BY ProductID;", conn)

    ProductID              ProductName  ProductModel                                            Summary
0         749         Road-150 Red, 62      Road-150  This bike is ridden by race winners. Developed...
1         750         Road-150 Red, 44      Road-150  This bike is ridden by race winners. Developed...
2         751         Road-150 Red, 48      Road-150  This bike is ridden by race winners. Developed...
3         752         Road-150 Red, 52      Road-150  This bike is ridden by race winners. Developed...
4         753         Road-150 Red, 56      Road-150  This bike is ridden by race winners. Developed...
5         754         Road-450 Red, 58      Road-450  A true multi-sport bike that offers streamline...
6         755         Road-450 Red, 60      Road-450  A true multi-sport bike that offers streamline...
7         756         Road-450 Red, 44      Road-450  A true multi-sport bike that offers streamline...
8         757         Road-450 Red, 48      Road-450  A true multi-sport bike that offers streamline...
9         758         Road-450 Red, 52      Road-450  A true multi-sport bike that offers streamline...
10        771  Mountain-100 Silver, 38  Mountain-100  Our top-of-the-line competition mountain bike....
11        772  Mountain-100 Silver, 42  Mountain-100  Our top-of-the-line competition mountain bike....
12        773  Mountain-100 Silver, 44  Mountain-100  Our top-of-the-line competition mountain bike....
13        774  Mountain-100 Silver, 48  Mountain-100  Our top-of-the-line competition mountain bike....
14        775   Mountain-100 Black, 38  Mountain-100  Our top-of-the-line competition mountain bike....
15        776   Mountain-100 Black, 42  Mountain-100  Our top-of-the-line competition mountain bike....
16        777   Mountain-100 Black, 44  Mountain-100  Our top-of-the-line competition mountain bike....
17        778   Mountain-100 Black, 48  Mountain-100  Our top-of-the-line competition mountain bike....
18        953    Touring-2000 Blue, 60  Touring-2000  The plush custom saddle keeps you riding all d...
19        954  Touring-1000 Yellow, 46  Touring-1000  Travel in style and comfort. Designed for maxi...
20        955  Touring-1000 Yellow, 50  Touring-1000  Travel in style and comfort. Designed for maxi...
21        956  Touring-1000 Yellow, 54  Touring-1000  Travel in style and comfort. Designed for maxi...
22        957  Touring-1000 Yellow, 60  Touring-1000  Travel in style and comfort. Designed for maxi...
23        966    Touring-1000 Blue, 46  Touring-1000  Travel in style and comfort. Designed for maxi...
24        967    Touring-1000 Blue, 50  Touring-1000  Travel in style and comfort. Designed for maxi...
25        968    Touring-1000 Blue, 54  Touring-1000  Travel in style and comfort. Designed for maxi...
26        969    Touring-1000 Blue, 60  Touring-1000  Travel in style and comfort. Designed for maxi...
27        970    Touring-2000 Blue, 46  Touring-2000  The plush custom saddle keeps you riding all d...
28        971    Touring-2000 Blue, 50  Touring-2000  The plush custom saddle keeps you riding all d...
29        972    Touring-2000 Blue, 54  Touring-2000  The plush custom saddle keeps you riding all d...
30        984  Mountain-500 Silver, 40  Mountain-500  Suitable for any type of riding, on or off-roa...
31        985  Mountain-500 Silver, 42  Mountain-500  Suitable for any type of riding, on or off-roa...
32        986  Mountain-500 Silver, 44  Mountain-500  Suitable for any type of riding, on or off-roa...
33        987  Mountain-500 Silver, 48  Mountain-500  Suitable for any type of riding, on or off-roa...
34        988  Mountain-500 Silver, 52  Mountain-500  Suitable for any type of riding, on or off-roa...
35        989   Mountain-500 Black, 40  Mountain-500  Suitable for any type of riding, on or off-roa...
36        990   Mountain-500 Black, 42  Mountain-500  Suitable for any type of riding, on or off-roa...
37        991   Mountain-500 Black, 44  Mountain-500  Suitable for any type of riding, on or off-roa...
38        992   Mountain-500 Black, 48  Mountain-500  Suitable for any type of riding, on or off-roa...
39        993   Mountain-500 Black, 52  Mountain-500  Suitable for any type of riding, on or off-roa...

In [ ]:
pd.read_sql_query("DECLARE @colors AS TABLE (Color nvarchar(15)) \
                   INSERT INTO @Colors \
                   SELECT DISTINCT Color FROM SalesLT.Product;", conn)

In [ ]:
pd.read_sql_query("SELECT ProductID, Name, Color \
                   FROM SalesLT.Product \
                   WHERE Color IN (SELECT Color FROM @Colors);", conn)

In [7]:
pd.read_sql_query("SELECT C.ParentProductCategoryName AS ParentCategory, \
                   C.ProductCategoryName AS Category,\
                   P.ProductID, P.Name AS ProductName \
                   FROM SalesLT.Product AS P \
                   JOIN dbo.ufnGetAllCategories() AS C \
                   ON P.ProductCategoryID = C.ProductCategoryID\
                   ORDER BY ParentCategory, Category, ProductName;", conn)

    ParentCategory           Category  ProductID             ProductName
0      Accessories         Bike Racks        876     Hitch Rack - 4-Bike
1      Accessories        Bike Stands        879  All-Purpose Bike Stand
2      Accessories  Bottles and Cages        871    Mountain Bottle Cage
3      Accessories  Bottles and Cages        872        Road Bottle Cage
4      Accessories  Bottles and Cages        870   Water Bottle - 30 oz.
..             ...                ...        ...                     ...
290     Components             Wheels        824  ML Mountain Rear Wheel
291     Components             Wheels        819     ML Road Front Wheel
292     Components             Wheels        827      ML Road Rear Wheel
293     Components             Wheels        821     Touring Front Wheel
294     Components             Wheels        829      Touring Rear Wheel

[295 rows x 4 columns]

## Challenge 2: Retrieve Customer Sales Revenue

In [8]:
pd.read_sql_query("SELECT CompanyContact, SUM(SalesAmount) AS Revenue \
                   FROM(SELECT CONCAT(c.CompanyName, CONCAT(' (' + c.FirstName + ' ', c.LastName + ')')), SOH.TotalDue \
                   FROM SalesLT.SalesOrderHeader AS SOH \
                   JOIN SalesLT.Customer AS c \
                   ON SOH.CustomerID = c.CustomerID) AS CustomerSales(CompanyContact, SalesAmount) \
                   GROUP BY CompanyContact \
                   ORDER BY CompanyContact;",conn)

                                       CompanyContact      Revenue
0        Action Bicycle Specialists (Terry Eminhizer)  119960.8240
1         Aerobic Exercise Company (Rosmarie Carroll)    2361.6403
2              Bulk Discount Store (Christopher Beck)   98138.2131
3        Central Bicycle Specialists (Janeth Esteves)      43.0437
4                      Channel Outlet (Richard Byham)     608.1766
5                 Closest Bicycle Store (Pamala Kotc)   39531.6085
6             Coalition Bike Company (Donald Blanton)    2669.3183
7                     Discount Tours (Melissa Marple)    3293.7761
8               Eastside Department Store (Kevin Liu)   92663.5609
9            Engineered Bike Systems (Joseph Mitzner)    3754.9733
10              Essential Bike Works (Linda Mitchell)      45.1995
11             Extreme Riding Supplies (Anthony Chor)   63686.2708
12                    Futuristic Bikes (Walter Brian)     272.6468
13                          Good Toys (David Hodgson)     972.7850
14     Instruments and Parts Company (Rebecca Laszlo)   70698.9922
15                   Many Bikes Store (Jeffrey Kurtz)   81834.9826
16  Metropolitan Bicycle Supply (Krishna Sunkammur...  108597.9536
17                 Nearby Cycle Shop (Raja Venugopal)   42452.6519
18         Paints and Solvents Company (Joyce Jarvis)   14017.9083
19    Professional Sales and Service (Catherine Abel)   43962.7901
20                 Remarkable Bike Store (Cory Booth)    7330.8972
21                         Riding Cycles (Jon Grande)   86222.8072
22                Sports Products Store (Walter Mays)    3673.3249
23                    Sports Store (Roger Van Houten)    2711.4098
24       Tachometers and Accessories (Matthew Miller)    2228.0566
25      The Bicycle Accessories Company (Guy Gilbert)     117.7276
26      Thrifty Parts and Sales (Michael John Troyer)    1261.4440
27                    Thrilling Bike Tours (Pei Chow)   15275.1977
28               Trailblazing Sports (Frank Campbell)   45992.3665
29                     Transport Bikes (Vassar Stern)     665.4251
30           Vigorous Sports Store (Brigid Cavendish)    1170.5376
31                    West Side Mart (Andrea Thomsen)      87.0851

In [9]:
conn.close()

#### Python code done by Dennis Lam